In [1]:
  pip install git+git://github.com/albertbup/deep-belief-network.git

  Cloning git://github.com/albertbup/deep-belief-network.git to /tmp/pip-req-build-kjuiwyul
  Running command git clone -q git://github.com/albertbup/deep-belief-network.git /tmp/pip-req-build-kjuiwyul
  Created wheel for deep-belief-network: filename=deep_belief_network-1.0.3-cp36-none-any.whl size=13462 sha256=d42c00fa76f1a92a82548a7f85885f1c1340b0d297e04e0cdc5ef1cff3589e44
  Stored in directory: /tmp/pip-ephem-wheel-cache-f2u0bxss/wheels/29/6d/3b/6a50cf42a32bdfaa903b17832d60d8d3e5dc4b0fd02ae8acaf
Successfully built deep-belief-network


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mpl
from sklearn.preprocessing import MinMaxScaler
from dbn import SupervisedDBNClassification, SupervisedDBNRegression
from sklearn.metrics import confusion_matrix
from sklearn.externals import joblib
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [0]:
from google.colab import files 

In [4]:
files.upload()

Saving Z Scores General Model 1 - Copy.csv to Z Scores General Model 1 - Copy.csv


{'Z Scores General Model 1 - Copy.csv': b'Facility Name,Hospital overall rating,Beds Available ,Doctors on Duty,Distance,Y\r\nNORTH TEXAS STATE HOSPITAL,3,19,19,28,0\r\nMAGEE GENERAL HOSPITAL,3,5,11,2,0\r\nCYPRESS CREEK HOSPITAL,3,7,7,12,0\r\nMARSHALL COUNTY HEALTHCARE CENTER - CAH,3,7,12,20,0\r\nJOHN SEED HOSPITAL,3,16,9,12,0\r\nST. HOPE HOSPITAL,3,17,13,11,0\r\nPARK ROYAL HOSPITAL,2,13,18,5,0\r\nGREENWICH HOSPITAL ASSOCIATION -,3,6,12,11,0\r\nKINGWOOD PINES HOSPITAL,3,6,5,5,0\r\nVETERANS MEMORIAL HOSPITAL,1,3,6,19,0\r\nPROVO CANYON BEHAVIORAL HOSPITAL,3,9,6,29,0\r\nMANHATTAN PSYCHIATRIC CENTER,4,20,19,10,1\r\nSUMMIT MEDICAL CENTER,2,4,19,1,0\r\nMCCURTAIN MEMORIAL HOSPITAL,5,4,7,22,1\r\nSELLS HOSPITAL,5,23,8,6,1\r\nOCEANS BEHAVIORAL HOSPITAL OF ABILENE,4,8,8,18,0\r\nBRATTLEBORO RETREAT,3,29,8,26,0\r\nGREENE COUNTY HOSPITAL,2,25,18,2,0\r\nCOMANCHE COUNTY HOSPITAL,2,30,14,18,0\r\nSUNDANCE HOSPITAL,2,27,11,27,0\r\nPATRICK B HARRIS PSYCHIATRIC HOSPITAL,4,18,15,18,1\r\nLBJ TROPICAL MEDICAL

In [5]:
df = pd.read_csv('Z Scores General Model 1 - Copy.csv')
df

Facility Name  ...  Y
0                  NORTH TEXAS STATE HOSPITAL  ...  0
1                      MAGEE GENERAL HOSPITAL  ...  0
2                      CYPRESS CREEK HOSPITAL  ...  0
3     MARSHALL COUNTY HEALTHCARE CENTER - CAH  ...  0
4                          JOHN SEED HOSPITAL  ...  0
...                                       ...  ... ..
4290                     CEDAR CREEK HOSPITAL  ...  0
4291               LAWRENCE MEMORIAL HOSPITAL  ...  0
4292             INSPIRA MEDICAL CENTER ELMER  ...  1
4293                  CITIZENS MEDICAL CENTER  ...  1
4294            NORTHERN MAINE MEDICAL CENTER  ...  1

[4295 rows x 6 columns]

In [6]:
dataset=df.values
dataset

array([['NORTH TEXAS STATE HOSPITAL', 3, 19, 19, 28, 0],
       ['MAGEE GENERAL HOSPITAL', 3, 5, 11, 2, 0],
       ['CYPRESS CREEK HOSPITAL', 3, 7, 7, 12, 0],
       ...,
       ['INSPIRA MEDICAL CENTER ELMER', 4, 10, 13, 4, 1],
       ['CITIZENS MEDICAL CENTER', 5, 16, 8, 9, 1],
       ['NORTHERN MAINE MEDICAL CENTER', 5, 9, 13, 2, 1]], dtype=object)

In [0]:
X = dataset[:,1:5]
Y = dataset[:,5]

In [8]:
scaler =  preprocessing.MinMaxScaler()
X_scale = scaler.fit_transform(X)
X_scale

array([[0.5       , 0.60714286, 0.93333333, 0.93103448],
       [0.5       , 0.10714286, 0.4       , 0.03448276],
       [0.5       , 0.17857143, 0.13333333, 0.37931034],
       ...,
       [0.75      , 0.28571429, 0.53333333, 0.10344828],
       [1.        , 0.5       , 0.2       , 0.27586207],
       [1.        , 0.25      , 0.53333333, 0.03448276]])

In [0]:
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.3)


In [0]:
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)

In [11]:

X_test

array([[0.75      , 0.89285714, 0.4       , 0.68965517],
       [0.5       , 0.5       , 0.06666667, 0.86206897],
       [0.75      , 0.57142857, 0.13333333, 0.10344828],
       ...,
       [0.25      , 0.35714286, 0.46666667, 0.17241379],
       [1.        , 0.32142857, 0.86666667, 0.13793103],
       [0.75      , 0.25      , 0.8       , 0.03448276]])

In [0]:
classifier = SupervisedDBNClassification(hidden_layers_structure=[200,200],
 learning_rate_rbm=0.01,
 learning_rate=0.1,
 n_epochs_rbm=200,
 n_iter_backprop=200,
 batch_size=32,
 activation_function='relu')

In [0]:
hist=classifier.fit(X_train, Y_train)

[START] Pre-training step:
>> Epoch 1 finished 	RBM Reconstruction error 0.058114
>> Epoch 2 finished 	RBM Reconstruction error 0.053494
>> Epoch 3 finished 	RBM Reconstruction error 0.050383
>> Epoch 4 finished 	RBM Reconstruction error 0.047245
>> Epoch 5 finished 	RBM Reconstruction error 0.045748
>> Epoch 6 finished 	RBM Reconstruction error 0.044085
>> Epoch 7 finished 	RBM Reconstruction error 0.042418
>> Epoch 8 finished 	RBM Reconstruction error 0.042674
>> Epoch 9 finished 	RBM Reconstruction error 0.041990
>> Epoch 10 finished 	RBM Reconstruction error 0.040770
>> Epoch 11 finished 	RBM Reconstruction error 0.040354
>> Epoch 12 finished 	RBM Reconstruction error 0.040698
>> Epoch 13 finished 	RBM Reconstruction error 0.040827
>> Epoch 14 finished 	RBM Reconstruction error 0.041307
>> Epoch 15 finished 	RBM Reconstruction error 0.040464
>> Epoch 16 finished 	RBM Reconstruction error 0.040204
>> Epoch 17 finished 	RBM Reconstruction error 0.039554
>> Epoch 18 finished 	RBM Reco

In [0]:
classifier.score(X_test,Y_test)

ValueError: ignored

In [0]:
Y_test
Y_test=np.asarray(Y_test).astype('int')
Y_val=np.asarray(Y_val).astype('int')
Y_test

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,

In [0]:
X_test.shape

(645, 4)

In [0]:
Y_pred = classifier.predict(X_val)
Y_pred=np.asarray(Y_pred)
Y_pred

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,

In [0]:
Y_test=np.asarray(Y_test).astype('int')
Y_val=np.asarray(Y_val).astype('int')

In [0]:
from sklearn.metrics.classification import accuracy_score
print('Done.\nAccuracy: %f' % accuracy_score(Y_val,Y_pred))

Done.
Accuracy: 0.998447


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.metrics.classification module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)
